### ISSUE TITLE
Patch work needed to make "cabal install haskakafka" work

### ISSUE THREAD

**Issue by madhavan020985** [cosbynator/haskakafka#10]
I am using ubuntu 14.04 with ghc - 7.8.4. When i ran cabal install haskakafka, it didn't work straight out of the box.

First, i had to do "sudo apt-get install librdkafka-dev" to solve, "* Missing C library: rdkafka" error.
Then i got the next error, 
````haskell
dist/build/Haskakafka/InternalRdKafka.chs.h:2:21: fatal error: rdkafka.h: No such file or directory
 #include "rdkafka.h"
````
I had to add librdkafka include path to my shell environment as,
````shell
export C_INCLUDE_PATH=/usr/include/librdkafka
````
If these two steps can be added in README page, then it will save other people's time. thanks.

**Comment by cosbynator** [comment]
Should be clarified in @jsermeno's update
