### ISSUE TITLE
Building & testing with stack

### ISSUE THREAD

**Issue by kjameslubin** [cosbynator/haskakafka#16]
I've managed to get haskafka to build and apparently to run. A key addition was to add the lines
```
extra-lib-dirs:
- /usr/local/lib
```
to the `stack.yaml`. 

Running example in Haskafka.Examples, I see the error
```
Woo, payload was Hello world
Woohoo, we got 10 messages
testkafka-exe: RdKafkaRespErrT.toEnum: Cannot match 32570
```
The tests in `tests` also fail with this message. Any insight into why this might be? 

Edit: I saw #9 after writing this - is there a sanctioned version of `librdkafka` to pull?

**Comment by sczizzo** [comment]
I've personally used HaskaKafka with librdkakfa versions 0.8.6 and 0.9.0 in [Theon](https://github.com/sczizzo/theon), but I did end up compiling librdkafka from source. I haven't tried the examples or tests in this repo, though.

**Comment by jsermeno** [comment]
I think this may be related to https://github.com/cosbynator/haskakafka/issues/20.

I'm using librdkafka v0.9.0.99. It turned out that c2hs was incorrectly sizing some of the C structs. Using the recent version of c2hs v0.28.1 has a fix.

**Comment by cosbynator** [comment]
I think this is addressed between 

https://github.com/cosbynator/haskakafka/pull/22

and 

https://github.com/cosbynator/haskakafka/pull/20

If this still persists, feel free to re-open the issue. Thanks!
