### ISSUE TITLE
Segmentation fault in fetchBrokerMetadata

### ISSUE THREAD

**Issue by jsermeno** [cosbynator/haskakafka#20]
Hi,

Thanks for the library. I receive a segfault when calling fetchBrokerMetadata per the example in the docs. The issue seems to be in `InternalRdKafka.hs`.

```
{#sizeof rd_kafka_metadata_broker_t#}
```

This line calculates the size of `rd_kafka_metadata_broker_t` to be 20. However, the size is really 24 with gcc v4.9.2 on Debian. The result is that in `getMetadata` in `Haskakafka.hs` calling `peekElemOff brokersPtr i` will create a bogus `RdKafkaMetadataBrokerT`.  The subsequent `peekCString (host'RdKafkaMetadataBrokerT bmd)` that occurs in `constructBrokerMetadata` is the line that causes the segfault.

There's an issue for this in haskell/c2hs: https://github.com/haskell/c2hs/issues/129. They state that using c2hs's current design, it's not possible to correctly compute the sizes in this instance due to limitations in what is available in `Foreign.Storable`.

I looked at other packages for deriving Storable instances, but they had the same issues. What do you suggest? I'm currently explicitly inserting the values in a local version of haskakafka. 

Similarly, the size of `rd_kafka_metadata_topic_t` should be 32. However, that doesn't cause a segfault, just an enum conversion error.

**Comment by takano-akio** [comment]
I believe this issue has been fixed in c2hs. See https://github.com/haskell/c2hs/issues/156.

**Comment by jsermeno** [comment]
Oh awesome. Thanks fantastic. I'll try it out.

**Comment by jsermeno** [comment]
That did the trick! If anyone else runs into the issue, updating to the resolver to `nightly-2016-04-05`, or a version that has c2hs v0.28.1 fixed the issue. Thanks for the heads up takano-akio.
