### ISSUE TITLE
Doesn't build against librdkafka >= 0.9.0.100

### ISSUE THREAD

**Issue by dbeacham** [cosbynator/haskakafka#27]
A few functions have moved/been renamed as of 0.9.0.100. At least:
- `rd_kafka_position` renamed to `rd_kafka_committed`
- `rd_kafka_position` has a new signature

Making the above changes enables compilation.

There's possibly other changes too - I'll have a browse through librdkafka > 0.9.0.99 commits to double check before sending over a PR.

**Comment by shajra** [comment]
Hi, this project is pretty valuable to me right now, and @dbeacham's commit is useful for the work in front of me.  I have to make some choices on what to tie to as a dependency (or whether to maintain my own fork).  Is this project still supported?  Is there any work we can help with to get this commit accepted?

**Comment by jsermeno** [comment]
I'll second @shajra's sentiment. I can help as well @cosbynator.

**Comment by shajra-cogscale** [comment]
@cosbynator @dbeacham @jsermeno this project feels like it's in limbo.  I have a feeling that both @cosbynator and @dbeacham used this project for a period of time, but then moved on.  As an FFI library, maintenance seems straight-forward, but it's still a commitment.  It would be really helpful to hear from either @cosbynator or @dbeacham about their ability to take ownership.  Mostly, there's a question of the release management on Hackage.  I'd like to avoid a fork/rename.  There's a process for claiming ownership if we can't get a hold of @cosbynator for some reason: https://wiki.haskell.org/Taking_over_a_package.  @jsermeno I think ownership would either fall on you or me.  And I'm happy sharing the ownership for some backup.  Anyway, I'll just give this post a week or so and see who responds.

**Comment by shajra** [comment]
[I accidentally posted this from a work account, so reposting this message with my normal GitHub account.]

@cosbynator @dbeacham @jsermeno this project feels like it's in limbo. I have a feeling that both @cosbynator and @dbeacham used this project for a period of time, but then moved on. As an FFI library, maintenance seems straight-forward, but it's still a commitment. It would be really helpful to hear from either @cosbynator or @dbeacham about their ability to take ownership. Mostly, there's a question of the release management on Hackage. I'd like to avoid a fork/rename. There's a process for claiming ownership if we can't get a hold of @cosbynator for some reason: https://wiki.haskell.org/Taking_over_a_package. @jsermeno I think ownership would either fall on you or me. And I'm happy sharing the ownership for some backup. Anyway, I'll just give this post a week or so and see who responds.

**Comment by dbeacham** [comment]
Hi all - the first interaction I had with the project was my above patch.

I'll reach out to @cosbynator to see if he has intention of maintaining the project. If not I'm happy to take ownership / contribute as necessary as there looks to be a new release of librdkafka in the near future.

**Comment by tolysz** [comment]
@dbeacham Well let's contribute against your branch :)

**Comment by cosbynator** [comment]
Hey, I've merged in that patch. I don't actively use haskakafka in production (was from a research project in school), so if someone else is a more appropriate maintainer then happy to pass off duties. Otherwise I can passively merge in patches and do the occasional release to hackage. Let me know!

**Comment by turtlesoupy** [comment]
@dbeacham  did a version bump and fixed builds on OSX sierra. 1.2.0 should be uploaded to hackage: https://hackage.haskell.org/package/haskakafka-1.2.0. Also uploaded 1.1.0 since that was never added.

**Comment by shajra** [comment]
@cosbynator thanks a ton for doing this.  I'll point my production builds from @dbeacham's fork to your latest work soon, and I'll report back (probably it will be working fine).

Personally, I don't mind who's the official maintainer.  Mostly, I was worried that you'd fallen off the map.  It might be nice to distribute ownership a little.  And also, if someone knows they're going to be unable to keep up, to chat with their backup.

My gut feeling is that we're all a little bit in the same boat -- kind of busy, and unsure how much time they can really commit to this.
